POST http://localhost:9999/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "titulo":"Aprende Node js",
    "Lenguaje":"node.js",
    "Nivel":"intermedio",
    "CapacidadEstudiantes":523
}